name: Validate Deployment
description: Shows deployed service and pod info, including Prometheus and Grafana.

inputs:
  AWS_ACCESS_KEY_ID:
    description: "AWS Access Key ID"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "AWS Secret Access Key"
    required: true
  AWS_REGION:
    description: "AWS Region"
    required: true
  AWS_ACCOUNT_ID:
    description: "AWS Account ID"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Update kubeconfig for EKS cluster
      shell: bash
      run: |
        aws eks update-kubeconfig --region ${{ inputs.AWS_REGION }} --name ci-cd-cluster

    - name: Show general service and pod info
      shell: bash
      run: |
        kubectl get svc
        kubectl get endpoints
        kubectl get pods
